services:
  - type: web
    name: wildai-cloud
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn wildlife_intrusion_api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MODEL_PATH
        value: yolov8n.pt
      - key: INFERENCE_INTERVAL
        value: "0.3"
      - key: CAMERA_ID
        value: ESP32_CAM_01
      - key: CAM_LAT
        value: "8.7599"
      - key: CAM_LON
        value: "77.1169"
      - key: ALLOWED_ORIGINS
        value: "*"
